---
title       : ShinyClusters
subtitle    : An App for Cluster Identification
author      : CP Montoya
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax, quiz, bootstrap]           # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## What is ShinyClusters?

* ShinyClusters is an app to identify clusters in two dimensional data

* The app is implemented on the web using Shiny from RStudio

* ShinyClusters uses the k-means algorithm available in r to identify the clusters

* ShinyCluster currently is limited to analyses of the iris data included in r

* The user can choose which two sets of data to use and how many clusters to identify

* The k-means algorithm randomly picks 25 starting centers and finds the best answer

* The user can compare k-means to the actual data with the "Show Actual Clusters" checkbox

* With 3 Clusters chosen the k-means compares favarably at least visually to the actual species

---

## How could one decide how many clusters to choose?

```{r fig.height=4,fig.width=8}
library(ggplot2)
pdata<-iris[c('Petal.Length','Sepal.Width')]
ydata<-sapply(c(1:10),function(x) kmeans(pdata,center=x,nstart=10)$tot.withinss)
lab<- c("Number of Clusters","Total Withinss")
qplot(c(1:10),ydata,geom="point",xlab=lab[1],ylab=lab[2],size=I(6))+geom_line(size=2)
```
* The elbow of the graph between two and three clusters indcates diminishing returns from adding clusters after 3 clusters, suggesting this might be an optimal choice

---

## What impovements could be made?

* Use "Choose File widget" to make it possible for user to select data to apply app to

* Perhaps use different starts to compute average cluster id (soft clusters rather than hard)

* Try to average across different data dimensions to impove accuracy

* Also try to offer PCA components as options for k-means dimensions to imporve accuracy

* Try to automate choice of number of clusters using plot of withinss versus number of clusters

---

## Check the app out for your self!

- The app can be found at this link: [http://cpmontoya.shinyapps.io/shinyClusters](http://cpmontoya.shinyapps.io/shinyClusters)

- You can look at the code on github here: [http://github.com/cpmontoya/shinyClusters.git](http://github.com/cpmontoya/shinyClusters.git)

